### ISSUE TITLE
Use gnuplot from env

### ISSUE THREAD

**Issue by vladov3000** [art-w/deque#1]
I get the following error when running the benchmarks:
```
$ make bench
[... omitted..]
dune exec --force tests/bench_append.exe > tests/bench.tsv && cd tests && ./bench.gp
Saving digest db.../bin/sh: ./bench.gp: /usr/bin/gnuplot: bad interpreter: No such file or directory
make: *** [bench] Error 126
```
This because I use the `brew` package manager on macos and gnuplot is NOT installed in /usr/bin but it is in my `PATH`. This is a 4 character fix in the bench.gp script header. Pull request incoming.

**Comment by art-w** [comment]
Thanks for the fix!
